name: golangci-lint

on: [push]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies(local)
        run: sudo apt-get update && sudo apt-get install -y libx11-dev xclip xsel
      - name: Install dependencies(go)
        working-directory: ./SecureChest
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./SecureChest

  govulncheck_job:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.22.11
           go-package: ./...
